version: "3.4"

services:
  hdfs-namenode:
    image: ntim/hadoop-hdfs-namenode:latest
    hostname: hdfs-namenode
    networks:
      - backend
    volumes:
      - hdfs-namenode:/var/hadoop
    ports:
      - 8020:8020
      - 50070:50070
  hdfs-datanode:
    image: ntim/hadoop-hdfs-datanode:latest
    networks:
      - backend
    ports:
      - 50075:50075
    volumes:
      - hdfs-datanode:/var/hadoop
    deploy:
      mode: global
  yarn-resourcemanager:
    image: ntim/hadoop-yarn-resourcemanager:latest
    hostname: yarn-resourcemanager
    networks:
      - backend
    ports:
      - 8088:8088
  yarn-nodemanager:
    image: ntim/hadoop-yarn-nodemanager:latest
    networks:
      - backend
    ports:
      - 8042:8042
    deploy:
      mode: global
    volumes:
      - yarn-nodemanager-logs:/usr/local/hadoop/logs
  zeppelin:
    image: ntim/zeppelin:latest
    hostname: zeppelin
    environment:
      - MASTER=yarn
    networks:
      - backend
    ports:
      - 8080:8080
    volumes:
      - zeppelin-notebooks:/usr/local/zeppelin/notebook
      - zeppelin-logs:/usr/local/zeppelin/logs

networks:
  backend:
    attachable: true

volumes:
  hdfs-namenode:
  hdfs-datanode:
  yarn-nodemanager-logs:
  zeppelin-notebooks:
  zeppelin-logs:
